#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

source "$(dirname "${BASH_SOURCE}")/lib/init.sh"

# Register function to be called on EXIT to remove generated binary.
function cleanup {
  rm -f "${DEEPCOPYGEN:-}"
}
trap cleanup EXIT

echo "Building deepcopy-gen"
DEEPCOPYGEN="${PWD}/deepcopy-gen-binary"
go build -o "${DEEPCOPYGEN}" ./vendor/k8s.io/kubernetes/cmd/libs/go2idl/deepcopy-gen

PREFIX=github.com/openshift/kube-projects

INPUT_DIRS=$(
  find . -not  \( \( -wholename '*/vendor/*' \) -prune \) -name '*.go' | \
  xargs grep --color=never -l '+k8s:deepcopy-gen=' | \
  xargs -n1 dirname | \
  sed "s,^\.,${PREFIX}," | \
  sort -u | \
  paste -sd,
)

${DEEPCOPYGEN} --logtostderr \
  --go-header-file ${OS_ROOT}/hack/boilerplate.txt \
  --bounding-dirs ${PREFIX} \
  --output-file-base zz_generated.deepcopy \
  --build-tag ignore_autogenerated_openshift \
  --input-dirs ${INPUT_DIRS[@]}
