#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

source "$(dirname "${BASH_SOURCE}")/lib/init.sh"

_tmp="${OS_ROOT}/_tmp"

function cleanup() {
  rm -rf "${_tmp}"
}
trap "cleanup" EXIT SIGINT

cleanup

APIROOTS=${APIROOTS:-pkg/project/api}

for APIROOT in ${APIROOTS}; do
  mkdir -p "${_tmp}/${APIROOT}"
  cp -a "${OS_ROOT}/${APIROOT}"/* "${_tmp}/${APIROOT}/"
done

${OS_ROOT}/hack/update-generated-protobuf.sh
for APIROOT in ${APIROOTS}; do
  TMP_APIROOT="${_tmp}/${APIROOT}"
  echo "diffing ${APIROOT} against freshly generated protobuf"
  ret=0
  diff -Naupr -I 'Auto generated by' -x 'zz_generated.*' "${OS_ROOT}/${APIROOT}" "${TMP_APIROOT}" || ret=$?
  cp -a "${TMP_APIROOT}"/* "${OS_ROOT}/${APIROOT}/"
  if [[ $ret -eq 0 ]]; then
    echo "${APIROOT} up to date."
  else
    echo "${APIROOT} is out of date. Please run hack/update-generated-protobuf.sh"
    exit 1
  fi
done
