// This package is generated by client-gen with arguments: --clientset-path=github.com/openshift/kube-projects/pkg/client/clientset_generated --go-header-file=/home/deads/workspaces/o-kube-projects/src/github.com/openshift/kube-projects/hack/boilerplate.txt --input=[./pkg/project/api] --input-base=github.com/openshift/kube-projects

// Package fake has the automatically generated clients.
package fake
